version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/app/logs
    ports:
      - "8080:8080"
    environment:
      - LOG_FILE_PATH=/app/logs/logs.log